### ISSUE TITLE
cordova-plguin-native Android bug fix

### ISSUE THREAD

**Issue by zhouzhongyuan** [BokeFE/QA#44]
- [Fix](https://github.com/zhouzhongyuan/cordova-plugin-native/commit/8925e3fcf76acff59197c47a53307835cf0f6873)
- 时间：2017年06月27日16:30
- 表现：点击按钮，不能进入。
- log:
```
06-27 16:26:26.292 8417-8417/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.bokesoft.zijiang, PID: 8417
                                                 java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.bokesoft.zijiang/com.cordova.plugin.nativeapp.HomeActivity}: java.lang.ClassNotFoundException: Didn't find class "com.cordova.plugin.nativeapp.HomeActivity" on path: DexPathList[[zip file "/data/app/com.bokesoft.zijiang-2/base.apk"],nativeLibraryDirectories=[/data/app/com.bokesoft.zijiang-2/lib/arm, /vendor/lib, /system/lib]]
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2253)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.cordova.plugin.nativeapp.HomeActivity" on path: DexPathList[[zip file "/data/app/com.bokesoft.zijiang-2/base.apk"],nativeLibraryDirectories=[/data/app/com.bokesoft.zijiang-2/lib/arm, /vendor/lib, /system/lib]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                     at android.app.Instrumentation.newActivity(Instrumentation.java:1066)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2243)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2404) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:154) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1315) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5290) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:911) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706) 
                                                 	Suppressed: java.lang.ClassNotFoundException: com.cordova.plugin.nativeapp.HomeActivity
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                     		... 13 more
                                                  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```
- 关键信息：
```
 java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.bokesoft.zijiang/com.cordova.plugin.nativeapp.HomeActivity}: java.lang.ClassNotFoundException: Didn't find class "com.cordova.plugin.nativeapp.HomeActivity" on path: DexPathList[[zip file "/data/app/com.bokesoft.zijiang-2/base.apk"],nativeLibraryDirectories=[/data/app/com.bokesoft.zijiang-2/lib/arm, /vendor/lib, /system/lib]]
```
```
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.cordova.plugin.nativeapp.HomeActivity" on path: DexPathList[[zip file "/data/app/com.bokesoft.zijiang-2/base.apk"],nativeLibraryDirectories=[/data/app/com.bokesoft.zijiang-2/lib/arm, /vendor/lib, /system/lib]]
```

**Comment by zhouzhongyuan** [comment]
# 任何一个bug都要做记录
# 任何一个bug都要做记录
# 任何一个bug都要做记录

**Comment by zhouzhongyuan** [comment]
# 时间线
## 1. 问题提出 
- 时间: 2017年06月28日 15:11
- 用时: 1h
- 参与人: 叁認壹木(日本人么~)，我
- 问题: 日本人说，紫江Android项目的Native版本打不开。
我说: 我明确记得日本人给我说过
> Android是好的

随找到聊天记录，证明此人确实说过。
![1](https://user-images.githubusercontent.com/717817/27616396-2844dca8-5be2-11e7-9e99-f3a15a716376.png)
给此人证据（10天后）之后，此人说他说的好是指”cordova部分“，并非指”Native部分“。

### 怪我，当时没有明确问。
教训：
### 任何问题都要有记录
### 给这些所谓的开发人员交流要名仔细，问明确。

这个问题解决后，我要问日本人

-  [ ] iOS下”cordova部分“是OK的吗？
-  [ ] iOS下”Native部分“是OK的吗？
-  [ ] Android下”cordova部分“是OK的吗？
-  [ ] Android下”Native部分“是OK的吗？

## 2. 与外包开发人员沟通
- 时间 2017年06月28日 16:30
- 用时: 2h
- 参与人: 两极，我
此开发人员自称具有2年Android端开发经验。但是他不懂Native开发和Web开发这两个名词的概念。
- 交流: 此次已经是第二次合并cordova部分与Android部分，但是第一次合并（由军亚和此人负责，军亚现已离职）的时候并没有形成任何文档，也没有任何约定。
- 总结:
    - 此人技术水平一般，不能称为一个合格的开发人员。
    - 不再与此人做无谓的沟通，自己看Android代码。
  -  [ ] 我完成后，形成文档，与此人约定下次合并的要求。
## 3. 研究Android代码
- 时间: 2017年06月29日 08:30
- 用时:
- 参与人: 我
### 3.1 重拾Android代码
- 时间: 2017年07月11日 11:00

**Comment by zhouzhongyuan** [comment]
# [Activity name 错误](https://github.com/zhouzhongyuan/cordova-plugin-native/commit/8925e3fcf76acff59197c47a53307835cf0f6873)
